databaseConfiguration:
    driver: mysql
    host: localhost
    port: 3306
    database: {{pac}}_{{user}}
    username: {{pac}}_{{user}}
    password: '{{password}}'
    charset: utf8mb4
    collation: utf8mb4_unicode_ci
    prefix: fl_
baseUrl: https://{{domain}}
adminUser:
    username: {{admin_user}}
    password: '{{admin_password}}'
    email: {{admin_email}}